- hosts: localhost
  become: true
  become_user: diggs
  tasks:
    - include_tasks: tasks/core-setup.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/nvim-setup.yml
    #- include_tasks: tasks/productivity-tools.yml
    #- include: tasks/lsp.yml
