- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    #- include: tasks/ssh.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/core-setup.yml
    #- include: tasks/node-setup.yml
    #- include: tasks/npm-packages.yml
    - include_tasks: tasks/zsh-setup.yml
    #- include: tasks/slack-setup.yml
    #- include: tasks/personal-projects.yml
    - include_tasks: tasks/nvim-setup.yml
    #- include: tasks/brave.yml
    #- include: tasks/debugger.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/productivity-tools.yml
    #- include: tasks/lsp.yml
